import type { NextPage } from 'next'
import Head from 'next/head'
import { trpc } from '../../utils/trpc'
import AppHeader from '../../components/app-header'
import { useRouter } from 'next/router'
import PostPreview from '../../components/post-preview'
import LoadingPageShell from '../../components/loading-page-shell'
import Image from 'next/image'

const Post: NextPage = () => {
  const router = useRouter()
  const { author } = router.query
  const authorInfo = trpc.useQuery([
    'blog.getAuthor',
    (Array.isArray(author) ? author[0] : author ?? '') as string,
  ])

  if (authorInfo.isLoading) {
    return <LoadingPageShell />
  }
  if (authorInfo.isError) {
    router.push('/')
  }

  return (
    <>
      <Head>
        <title>{authorInfo.data?.name ?? '[Author]'}&apos;s Posts</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col">
        <AppHeader>
          <div className="flex items-center justify-between border-b border-b-gray-400 bg-emerald-200/60 py-6 px-4 backdrop-blur backdrop-filter">
            <div className="flex items-center gap-2">
              {authorInfo.data?.image && (
                <div className="relative h-6 w-6 overflow-hidden rounded-full shadow">
                  <Image alt="" layout="fill" src={authorInfo.data.image} />
                </div>
              )}
              <p className="text-lg">{authorInfo.data?.name}</p>
            </div>
          </div>
        </AppHeader>
        <div className="m-4 grid gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
          {authorInfo.data?.Posts.map((post) => (
            <PostPreview
              post={{
                ...post,
                author: {
                  id: authorInfo.data!.id,
                  image: authorInfo.data!.image,
                  name: authorInfo.data!.name,
                },
              }}
              key={post.id}
            />
          ))}
        </div>
      </div>
    </>
  )
}

export default Post
