import type { NextPage } from 'next'
import Head from 'next/head'
import { trpc } from '../utils/trpc'
import Link from 'next/link'
import { useSession } from 'next-auth/react'
import AppHeader from '../components/app-header'
import PostPreview from '../components/post-preview'

const Home: NextPage = () => {
  const { status } = useSession()
  const posts = trpc.useQuery(['blog.getAll'])

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col">
        <AppHeader>
          <div className="flex items-center justify-between border-b border-b-gray-400 bg-emerald-200/60 py-12 px-4 backdrop-blur backdrop-filter">
            <p className="text-xl">quick blog made with the T3 stack</p>
            {status === 'authenticated' && (
              <Link href="/post">
                <a className="rounded-lg bg-emerald-600 px-2 py-1 text-base font-semibold text-emerald-50">
                  Create Post
                </a>
              </Link>
            )}
          </div>
        </AppHeader>
        <div className="m-4 grid gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
          {posts.data?.map((post) => (
            <PostPreview post={post} key={post.id} />
          ))}
        </div>
      </div>
    </>
  )
}

export default Home
